server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhb_dormitory?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
